### ISSUE TITLE
Music for non donators is too short.

### ISSUE THREAD

**Issue by AdminHole** [Mantaro/MantaroBot#102]
I feel it is too short Most bots have a 60min max for non donators and I never seen a bot with a max of 32 Minutes It should be at least 60Mins Also noticed that music sometimes has A lot of lag spikes. But overall the bot is Amazing! If you need to DM me contact me on discord at @❄YourNormal🅰dmin❄#6506

**Comment by Kodehawa** [comment]
did you try to switch voice region to something like US East or US West to fix ur issues.
West Europe should work too

**Comment by MrLar** [comment]
Lag spikes can be caused by Discord depending on your Voice Region, the regions that usually (but not always are) lag free are the ones close to US East (i.e almost all US regions). They can also be affected by *your* connection.

And as for song duration limit. Well, its a music bot and most tracks are longer than 10 minutes, so we choose 32 as a resource friendly time for our server etc.
You can hover queue entire playlists and stuff, on top of that to get your music to an unlimited limit its basically just 1 dollar thats all.

**Comment by natanbc** [comment]
^

**Comment by MrLar** [comment]
Also for "extended" versions you can just do `~>repeat`
