### ISSUE TITLE
~>custom commands

### ISSUE THREAD

**Issue by BlackRockShooter007** [Mantaro/MantaroBot#128]
Id like to know how to make a command just like e.g: "~>slap @mention" but instead "~>punch @mention" if possible with custom commands

**Comment by MrLar** [comment]
You cannot upload an image using custom commands but you can hover get close by using embeds `embed:description:"your text here,image:"your url here"` keep in mind the url must be direct. Also since there is no mention modifier the closest you'll get to fetch the mention is $(event.mesaage.raw). For more info on custom commands and their modifiers be sure to click the wiki button at the top and head to the respective sections.

**Comment by BlackRockShooter007** [comment]
id like the command to target someone when mentioned, i can make a custom
command that sends a gif or image easily but it wont target the person like
the normal commands

**Comment by MrLar** [comment]
Like I mentioned there is no direct way to target the mentioned person the only work arround is the one I mentioned in my comment.

**Comment by BlackRockShooter007** [comment]
so in other words theres no way for me to replicate an action command that
already exists just with a different name

**Comment by MrLar** [comment]
Not to an extensive level at least as of now. You will be able to in the rewrite of custom commands but that won't be published until v5.0

**Comment by natanbc** [comment]
The images will still need to be in embeds btw

**Comment by BlackRockShooter007** [comment]
thanks for the help guess ill just have to wait for targeting commands to
be make-able in 5.0v
