### ISSUE TITLE
Creating text/gif with no link to the gif.

### ISSUE THREAD

**Issue by Crowbare** [Mantaro/MantaroBot#148]
So I've been working on making my own version of the gif commands but have been unable to remove the link to the gif when the command is used. The exception being when I put the gif link without the text. As an example.

->custom new spank imgembed:http://i0.kym-cdn.com/photos/images/newsfeed/001/052/135/0a9.gif

This will show just the gif without the link yet if I do

->custom new spank $(event.message.stripped) you have been spanked by $(event.author.username).  imgembed:http://i0.kym-cdn.com/photos/images/newsfeed/001/052/135/0a9.gif

It will show both the text and picture but also the link. Is there a way to do hide the gif link or perhaps send out two seperate messages so that the first is the text and the second is the gif without a link?

**Comment by MrLar** [comment]
That is because this is now how custom commands work you cannot have an image and raw text at once. If you wanna have text along side your image you need to do something like this:

embed:description:"<your text here>",image:"<your url here>"

Also for future support questions please refer to our [support guild and the support channel](https://discord.gg/uMYAyES)

**Comment by Crowbare** [comment]
Okay my bad! Thanks, for answering so fast!
