### ISSUE TITLE
EST timezone is an hour early?

### ISSUE THREAD

**Issue by gt-c** [Mantaro/MantaroBot#155]
When running `.time EST` I get `It's 15-Apr-2018 03:30:12 PM in the EST timezone`. When it is actually 04:30:12 PM. I don't know if this is a bug or a desired result

**Comment by MrLar** [comment]
Foreword: Due to a bug ~>time always displays your profile timezone

This is technically correct due to how Daylight saving times work. EST is the time observed during winter and as of this post its 16:10 in EST (which mantaro correctly displays when using EST). However currently EST is not being observed because well its spring and spring uses Summer time which is EDT, EDT is 1 hour ahead of EST and is currently as of this post at 17:10 (which Mantaro would correctly display but unfortunately it doesn't recognize it as a time zone). Your best bet is to use your actual location, for Instance I would use ~>time Europe/Berlin, if the bug mentioned in the foreword is fixed, as of now you would use it by setting your profile timezone to your location for me that would be ~>profile timezone Europe/Berlin. Hope this helps.
