### ISSUE TITLE
Lock Mantaro to a text channel

### ISSUE THREAD

**Issue by PatPeter** [Mantaro/MantaroBot#177]
I know that it is possible to lock Mantaro to a text channel, but I want to lock Mantaro to only read input from a specific text channel so that Mantaro output and spam isn't posted all over my Discord. Is this possible for me to implement with permissions or no?

**Comment by MrLar** [comment]
You can either achieve this with our various [command/channel disabling features](https://github.com/Mantaro/MantaroBot/wiki/Configuration#disabling-commands--channels--categories) or the more sane approach would be to remove the Administrator permission from it (if it has it) and then handle it with channel permissions within discord itself so that Mantaro can only actually see that channel
