### ISSUE TITLE
Selling and Buying Floppy Disk

### ISSUE THREAD

**Issue by vhylace** [Mantaro/MantaroBot#187]
For some reason Mantaro doesn’t recognize floppy disk as an item in the market, but you can you retrieve it from ->loot.

**Comment by MrLar** [comment]
Floppy disk have never been purchasable and never will be they are meant to be only obtainable from loot after playing games (though this has been temporarily disabled, further info below)

As for selling, yes they are meant to be sell-able thought this has been disabled as well as the dropping of them and almost every collectible item due to people abusing the commands (aka. spamming them with self/user bots to gain a lot very quick with dirty measures). There is no estimated time as to when they will return back to normal, but it won't happen until we found a proper way to punish/deal with abuse on an automated base.
