### ISSUE TITLE
[ Feature Req. ] Special Badges

### ISSUE THREAD

**Issue by allanf181** [Mantaro/MantaroBot#247]
Badges for people who have been using Mantaro since it started or who have been banned from the Mantaro Hub for no reason.

~~I think Adrian still hates me.~~

**Comment by adriantodt** [comment]
Totally unrelated to the issue itself:

![](https://i.imgur.com/TeenXdW.png)
I don't hate you, blame my server. ¯\\\_(ツ)\_/¯

**Comment by adriantodt** [comment]
About the feature request, Kode is the one who has the final word but:
- We can't exactly trace who used Mantaro since the start.
    - Actually we might by using some data.json files that might be wandering around on hard drives BUT it's totally unreliable also it'd be a badge literally added by a program that for-looped a user keySet of the data.json of god-knows-where. So that's a prolly no.
- Adding badges for being banned on MH = Giving people a reason to act toxic on MH on purpose. We have enough raids per year already, more people being toxic would be IQ -1000. That's also a prolly no.

**Comment by Kodehawa** [comment]
what a meme

**Comment by allanf181** [comment]
I still do not know why I got banned from  Mantaro Hub. I do not even remember talking there.
