### ISSUE TITLE
[ Bug ] Daily streak unfairly reset.

### ISSUE THREAD

**Issue by Link5261** [Mantaro/MantaroBot#258]
**Describe the bug**
Attached is a screenshot showing the timestamps of two `?daily` commands, separated by more than 24 hours, but less than 48 hours. My claim streak of 350x was reset, even though two days had not passed as mentioned by the accompanying message.
![Untitled](https://user-images.githubusercontent.com/43685379/54861088-eb508080-4cf9-11e9-81bd-c4639737bfd1.png)

**To Reproduce**
Get ultra-unlucky with the `?daily` command, I guess.

**Expected behavior**
I expected my daily streak to continue to grow to 351x and my daily reward of $1000.

**Comment by Kodehawa** [comment]
This happened because you used fishing RIGHT BEFORE DAILY, without giving it any time to actually save your profile. You cann see it because it replied with the fishing message AFTER the daily message. 

Basically, it saved a profile snapshot of fish and not of daily, which made you lose your streak. Sorry.

**Comment by Link5261** [comment]
The bot was delayed. Typically, by the time I type out the next command to enter, the prior one has completed. I was never aware that it hadn't saved my progress / time snapshot since the message response regarding `?daily` was typical and a success, _plus_ the non-pictured, but mentioned attempt to `?daily` again when it told me a cooldown timer, which I only exceeded by about 6 hours. Does this mean the bot saved the timeout limit but not the success status?

**Comment by Kodehawa** [comment]
The bot basically works in this way:
Start command -> grab player snapshot -> save

If two commands run at the same time, only the one that finishes the last will be saved, since that one will save the snapshot of the player that it saw first. We're talking about a few ms of difference here on the processing on the two commands.

As for your question: Basically, yes.

**Comment by Link5261** [comment]
Thanks for the expedient response, @Kodehawa. I guess the issue has been sufficiently explained.

**Comment by neihousaigaai** [comment]
Today I got this issue.

I have typed `->daily` before fishing, but the daily streak has been reseted.

![image](https://user-images.githubusercontent.com/19959482/71324681-6c9ca400-2514-11ea-9926-83b8b46da015.png)

**Comment by DrGilderoy** [comment]
I lost my streak even though I didn't use fishing or mining commands before the daily command
Can it be applied back to my profile?

![Discord_4iwXabYrBL](https://user-images.githubusercontent.com/43506851/72664487-cfdc0200-39fe-11ea-9395-272bc3a69826.png)
![Discord_DvPqmQbOpi](https://user-images.githubusercontent.com/43506851/72664488-cfdc0200-39fe-11ea-92ca-c2e493b207f7.png)
![Discord_UUx5pnrHvL](https://user-images.githubusercontent.com/43506851/72664489-cfdc0200-39fe-11ea-86b3-56a5b9dd26fc.png)

**Comment by Kodehawa** [comment]
Please post about it in #support and ping Kodehawa#3457 about it.
