### ISSUE TITLE
[ Bug ] I can't equip my diamond pickaxe no matter what I do. even the command

### ISSUE THREAD

**Issue by 0koroshiya0** [Mantaro/MantaroBot#277]
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [x] Made sure this is actual unintended behaviour.
- [x] Double checked the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) for potential misunderstandings.
- [x] Double checked `~>help <command name>` (if this is command related) for potential misunderstandings.

**Describe the bug**
I first made the diamond pickaxe then tried to mine with it. It then said "You don't have a pick to mine with, while I still had my diamond pickaxe in my inventory. Then it said "If you want to use any other pick, do ~>mine  <pick  name>. I did exactly that.

**To Reproduce**
Steps to reproduce this behavior (if applicable): try and fix said problem

**Expected behavior**
I expected it to let me equip this so I can use it.

**Additional context**
Add any other context here or remove this section entirely.

**Comment by MrLar** [comment]
I dont know what your issue is as the mine command will tell you to try another pickaxe when you dont have the default one. Based on your description however you just tried to do mine again without specifying a pickaxe. Your heading also talks about equip a pickaxe but never did you actually talk about equipping not working just about mining not working, in an intentional way. Without you giving us clear steps to replicate this issue (which the steps to reproduce field is for btw not for telling us to fix the issue) we cant really do anything.

**Comment by 0koroshiya0** [comment]
for some reason it cut off. What it said was~>mine  <pick name> was the input. Then when i tried to input the command, it said the same thing because it had the command ~>mine in it.

**Comment by 0koroshiya0** [comment]
it did it again

**Comment by 0koroshiya0** [comment]
it said "pick name" after the mine thing

**Comment by MrLar** [comment]
If you are trying to mine with a diamond pickaxe simply do ~>mine diamond pickaxe

**Comment by 0koroshiya0** [comment]
it finally worked, thank you MrLar!
