### ISSUE TITLE
found a possible bug

### ISSUE THREAD

**Issue by Kazuhiro-sama** [Mantaro/MantaroBot#53]
to keep it simple. when using the ->love command and the percentage generated is 45% it reads "Perfect match!" which should be the line for 100% if i'm not mistaken. would be a weird thing to jump from 'try again later' lines to perfect and then to just "Good enough." only to start gradually increasing after that

**Comment by Desiiii** [comment]
I think I have found where this is in the code. It seems to happen because it uses an "else" for the perfect match bit.
http://prntscr.com/g6uf6q
if you got 45 or 75, it would generate a Perfect Match, as they aren't defined themselves, just numbers higher and lower from them.
Just placing this as a reference so the devs would know where this issue would be.

**Comment by Kodehawa** [comment]
That's how it normally goes. Something failed at 45% so yeah, I might check on that later ;)

btw, can you provide an screenshot?

**Comment by Kodehawa** [comment]
Fixed as on https://github.com/Mantaro/MantaroBot/commit/dc241421f9262962c1c274477740e9ab34bd92b0
