### ISSUE TITLE
[Feature request/suggestion] Alias command

### ISSUE THREAD

**Issue by TheRealZuggy** [Mantaro/MantaroBot#604]
**Before submitting I have**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [x] Double checked existing Issues/Pull Requests for a similar feature.

**Describe what you would like us to add**
Since there's already a way to rename custom commands I'd really like to see a way to rename or add an alias to regular commands. So for example it would be like "->alias add play p" and after that whenever I type ->p it would be the same as typing ->play. Aside from ->alias add I would suggest ->alias remove and ->alias list.

**Comment by MrLar** [comment]
First of all play actually already has the alias "p" (you can check existing aliases of existing commands on `~>help <command>`).
Now to the actual feature request, we have actually had this feature requested a couple of times before and it has been rejected every time due to being too intensive for our end (as hundreds of thousands of servers could have hundreds if not more custom aliases). Keep in mind that this would also not be the same as renaming a custom command, because when you rename that custom we only store the new name as the old one simply gets discarded, where as with aliases both (or more if one were to set more) would still work. On top of being incredibly intensive on our end it would also be very confusing for users new to Mantaro as they would see people doing aliases that do not work out of the box (we get enough inquiries about why a prefix or a [custom] command does not work on support).
All of that being said I'm going to leave the final word up to @Kodehawa. He can either just close this or add more to it if he sees fit.

**Comment by Kodehawa** [comment]
Impossible with slash commands.
