### ISSUE TITLE
I can't hear the music but others can

### ISSUE THREAD

**Issue by MsTTTess** [Mantaro/MantaroBot#98]
So I got the sound on 200%, I have not muted the bot. But I cant hear the music from the bot but everyone else can. :/

**Comment by Kodehawa** [comment]
I think you realize this is because of an issue in your end and not in the bot's end.

Try the following:

- Leave and join the voice channel (you, not the bot)
- Go to audio settings on discord and make sure the correct output device is selected.
- Reboot your computer (hold shift while hitting the reboot button to trigger a cold reboot under windows 10 fall creators update).
- Check your audio drivers & devices.

**Comment by MsTTTess** [comment]
I know it wasn't the bots fault, but thanks for the help :)

**Comment by MsTTTess** [comment]
And I'd like to say that mantaro is the only bot I can't hear the music from :)

**Comment by Kodehawa** [comment]
I cannot help with non-bot issues besides the usual troubleshooting mechanics. Something is wrong on *your* end

**Comment by Kodehawa** [comment]
Try killing the discord process and starting it again, lol.
